version: "3.8"

services:
  #frontend:
  #  build: ./frontend
  #  container_name: frontend
  #  ports:
  #    - "5173:5173"
  #  networks:
  #    - app-network

  eureka:
    build: ./eureka
    container_name: eureka_server
    ports:
      - "8761:8761"
    networks:
      - app-network

  gateway:
    build: ./gateway_acl
    container_name: gateway_acl
    ports:
      - "8762:8762"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
    networks:
      - app-network

  ms-users:
    build: ./ms-users
    container_name: ms-users
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
    networks:
      - app-network

  ms-matches:
    build: ./ms-matches
    container_name: ms-matches
    env_file:
      - .env
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
    networks:
      - app-network
    ports:
      - "8081:8081"

  ms-bookings:
    build: ./ms-bookings
    container_name: ms-bookings
    env_file:
      - .env
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
    networks:
      - app-network
    ports:
      - "8082:8082"

  ms-clubs:
    build: ./ms-clubs
    container_name: ms-clubs
    env_file:
      - .env
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
    networks:
      - app-network
    ports:
      - "8083:8083"

  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes: #Guarda los datos de MySQL en un volumen persistente
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: