spring:
  application:
    name: ms-bookings
  datasource:
    url: jdbc:h2:mem:testdb;Mode=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true # Allow access from web


# Configuración de instancia
server:
  port: 8082

#Configuración Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: ms-bookings