spring:
  application:
    name: ms-users
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ms-users}
    driverClassName: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  #h2:
  #  console:
  #    enabled: true
  #    path: /h2-console
  #    settings:
  #      web-allow-others: true # Allow access from web


# Configuración de instancia
server:
  port: 8080

#Configuración Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: ms-users